env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:   
  no-console: 0
  import/prefer-default-export: 0
  no-param-reassign: ["error", { "props": false }]
  import/extensions: ["error", "ignorePackages", {
      "js": "always",
    }]
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]